jobs:
  include:
    - name: Linux | Python 3.6
      os: linux
      language: python
      python: '3.6'
      sudo: required
      dist: xenial

    - name: Linux | Python 3.7
      os: linux
      language: python
      python: '3.7'
      sudo: required
      dist: xenial

    - name: MacOSX | Python 3.7 (Catalina, 10.15)
      os: osx
      osx_image: xcode12
      language: shell
      env: TRAVIS_PYTHON_VERSION=3.7

    - name: Windows | Python 3.7
      os: windows
      language: shell
      env: TRAVIS_PYTHON_VERSION=3.7

    - stage: deploy
      name: Publish nightly package
      os: linux
      language: python
      python: '3.7'
      sudo: required
      dist: xenial
      install: skip
      script: skip
      after_success: skip
      deploy:
        edge: true
        provider: pypi
        username: __token__
        password:
          secure: b67LO8VZcoKEWo7gDlFdjS1yKUavCt578uAuXPyW6f+e+Tk/sEQRdkx1VYoZlQdfZQo8u4q+E3W184T+/j6ht65/cdy/HYH57LCQySjF/MY2M9+/lcP45aY7Z0F2QHeY9QgpRc8gKthGzgM/bHj2glxlEvT1diItEEoGqE2x/fw1K25cNOni08E4hqz0HPY1SXVwd8/9Z/t1YasrBcOjtJ8kcbyjnmeyhjfkaV/aTaAzuqh2MlqZTSz3dhwsBrZfZp86+8T2TgcoDSuIxCwb777QKW1QlvNyLEKlnfateKMYqrrP65oHrxXEEcHd/N3IH28Bz9wVnENjHLkGJ0vXyXyEWcJFe+V6T0k/8NkZamU4SZE5BM4v6mOdThs4l54vuFajctHDeGgIDjL55MfkDmkKd5lAvlWPwrdw8DERsmqetUfZ/TG7FE6/MT1puu2ffu3A9Ivcch5T46pojIggDWHHn9hUsc6iD3Ov7rVqd024Lzm9V8wXiDYU9EMqAu5lJQRIOO/hnr8Gn6zYRCE1n29MKuNJwauSHfdV/mBTRyOjZyWHSGNaiPw2hqE3tZrrIN4koEYaZiERRVnmVt8wMUTj40YglosTHYpL91SkDH/ResX1rtHKs4Am+R+MmcWULTUQ7UwEtqlsa3nVxTK9gfmJ0nX8Jhjtl2iRhVg5PP8=
        on:
          tags: true
          branch: master
        skip_existing: true

cache: pip
before_install:
  # `libomp` is needed for XGBoost and LightGBM
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update && brew install libomp
    fi
install:
  - source ./scripts/install_miniconda.bash
  - source ./scripts/install_deepchem_conda.bash $TRAVIS_PYTHON_VERSION cpu
  - conda activate deepchem
  - pip install -e .
script:
  - source ./scripts/yapf_for_ci.bash
  - source ./scripts/flake8_for_ci.bash
  - mypy -p deepchem
  - pytest -v -m "not slow" --cov=deepchem deepchem
  - pytest -v --ignore-glob='deepchem/**/test*.py' --doctest-modules deepchem
after_success:
  - echo $TRAVIS_SECURE_ENV_VARS
  - coveralls
