matrix:
  include:
    - sudo: required
      os: linux
      env: python_version=2.7

    - sudo: required
      os: linux
      env: python_version=3.5

    - os: osx
      env: python_version=2.7
      language: objective-c

    - os: osx
      env: python_version=3.5
      language: objective-c



install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O anaconda.sh;
- export python_version=$TRAVIS_PYTHON_VERSION
- bash anaconda.sh -b -p $HOME/anaconda
- export PATH="$HOME/anaconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -y --name deepchem python=$python_version
- source activate deepchem
- conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem-deps=1.2.1
- pip install coveralls
- python setup.py install
script:
- nosetests --with-flaky -a '!slow' --with-timer --with-coverage --cover-package=deepchem -v deepchem --nologcapture
- find ./deepchem | grep .py$ |xargs python -m doctest -v
- bash devtools/travis-ci/test_format_code.sh
after_success:
- echo $TRAVIS_SECURE_ENV_VARS
- coveralls
