name: 'Docker Build Test'

on:
  pull_request:

permissions:
  contents: read

jobs:
  Test-Docker:
    runs-on: ubuntu-latest
    name: 'Test-Docker'

    steps:
    - name: Maximize build space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /usr/local/lib/android

    - name: Checkout
      uses: actions/checkout@v4

    - name: Dockerise
      run: |
        cd docker/nightly
        sudo docker build -t test-image .
